#!/bin/bash

# Create NoteBook, and all its plug-ins
# This script must be run from the top-level NoteBook directory.


# Build NoteBook itself
pushd Src/NoteBook/NoteBook
make clean
popd

pushd Src/RichTextEditor
make clean
popd

pushd Src/FolderEditor
make clean
popd

pushd Src/ToDoListEditor
make clean
popd

pushd Src/ImportNoteBook/ImportNoteBook
make clean
popd

pushd Src/ImportTiddlyWiki/ImportTiddlyWiki
make clean
popd
