#ifndef RICHTEXTEDITOR_GLOBAL_H
#define RICHTEXTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RICHTEXTEDITOR_LIBRARY)
#  define RICHTEXTEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RICHTEXTEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RICHTEXTEDITOR_GLOBAL_H
