#ifndef TODOLISTEDITOR_GLOBAL_H
#define TODOLISTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TODOLISTEDITOR_LIBRARY)
#  define TODOLISTEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TODOLISTEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TODOLISTEDITOR_GLOBAL_H
